// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './yuji-syuku.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Yuji Syuku',
  lineCap: 'butt',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Yuji Syuku'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1160,
  descender: -288,
  glyphData,
} as const;

export default bundle;
